name: Gitleaks Secret Scan
on: [push, pull_request]

jobs:
    gitleaks:
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
              with:
                egress-policy: audit

            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
              with:
                  fetch-depth: 0
            - uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
